services:
    devcontainer:
        build:
            dockerfile: DockerFile
        restart: always
        command: sleep infinity
        volumes:
            - ../:/app/:cached
            - npm-cache:/home/vscode/.npm
            - satisfactory-dev_docsdotjsonts_generated_data_only:/app/generated-types/

volumes:
    npm-cache:
        external: true
    satisfactory-dev_docsdotjsonts_generated_data_only:
        external: true
