services:
    devcontainer:
        build:
            dockerfile: DockerFile
        restart: always
        command: sleep infinity
        volumes:
            - ../:/app/:cached
            - npm-cache:/home/vscode/.npm

volumes:
    npm-cache:
        external: true
